spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecsite
    username: postgres
    password: postgres

logging.level:
  org.springframework: WARN    